//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemOfUnitsGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemOfUnitsGenerator.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string NamespaceAngle {
            get {
                return ResourceManager.GetString("NamespaceAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalInformation.Bit.
        /// </summary>
        internal static string NamespaceBit {
            get {
                return ResourceManager.GetString("NamespaceBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalInformation.Byte.
        /// </summary>
        internal static string NamespaceByte1000 {
            get {
                return ResourceManager.GetString("NamespaceByte1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalInformation.Byte.
        /// </summary>
        internal static string NamespaceByte1024 {
            get {
                return ResourceManager.GetString("NamespaceByte1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.CubicMetre.
        /// </summary>
        internal static string NamespaceCubicMetre {
            get {
                return ResourceManager.GetString("NamespaceCubicMetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string NamespaceCurrency {
            get {
                return ResourceManager.GetString("NamespaceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.Gram.
        /// </summary>
        internal static string NamespaceGram {
            get {
                return ResourceManager.GetString("NamespaceGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.Hertz.
        /// </summary>
        internal static string NamespaceHertz {
            get {
                return ResourceManager.GetString("NamespaceHertz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.Imperial.
        /// </summary>
        internal static string NamespaceImperialLength {
            get {
                return ResourceManager.GetString("NamespaceImperialLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.Joule.
        /// </summary>
        internal static string NamespaceJoule {
            get {
                return ResourceManager.GetString("NamespaceJoule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.Litre.
        /// </summary>
        internal static string NamespaceLitre {
            get {
                return ResourceManager.GetString("NamespaceLitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.Metre.
        /// </summary>
        internal static string NamespaceMetre {
            get {
                return ResourceManager.GetString("NamespaceMetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string NamespaceOthers {
            get {
                return ResourceManager.GetString("NamespaceOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigitalInformation.Pixel.
        /// </summary>
        internal static string NamespacePixel {
            get {
                return ResourceManager.GetString("NamespacePixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.SquareMetre.
        /// </summary>
        internal static string NamespaceSquareMetre {
            get {
                return ResourceManager.GetString("NamespaceSquareMetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string NamespaceTemperature {
            get {
                return ResourceManager.GetString("NamespaceTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string NamespaceTime {
            get {
                return ResourceManager.GetString("NamespaceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.Watt.
        /// </summary>
        internal static string NamespaceWatt {
            get {
                return ResourceManager.GetString("NamespaceWatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemOfUnits.
        /// </summary>
        internal static string SystemOfUnits {
            get {
                return ResourceManager.GetString("SystemOfUnits", resourceCulture);
            }
        }
    }
}
